version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: support-chat-db
    restart: always

    environment:
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: support_pass
      POSTGRES_DB: support_chat
    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U support_user -d support_chat"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: